
version: '2.0'

services:
  lnmp:
    build:
      context: .
      dockerfile: Dockerfile
    image: 'lnmp:latest'
    volumes:
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./php/7.4/fpm:/etc/php/7.4/fpm
      - ./mysql/mysql.conf.d/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./www/:/var/www/html
      - ./log/mysql:/var/log/mysql
      - ./log/nginx:/var/log/nginx
      - ./log/php/php.log:/var/log/php7.4-fpm.log
    environment:
      - TZ=Asia/Shanghai
    ports:
      - 80:80
      - 3306:3306
    container_name: lnmp  