version: "3"
services:
    nginx:
        image: nginx:latest
        container_name: "compose-nginx"
        restart: always
        ports:
            - "80:80"
            - "443:443"
        environment:
           - TZ=Asia/Shanghai
        volumes:
           - "./conf.d:/etc/nginx/conf.d"
           - "./www:/usr/share/nginx/html"
           - "./log:/var/log/nginx"
        networks:
           - net-app
    redis:
      image: redis
      container_name: "compose-redis"
      restart: always
      command: /bin/bash -c "redis-server /usr/local/etc/redis/redis.conf"
      ports:
        - "6379:6379"
      volumes:
        - "./redis/data:/data:rw"
        - "./redis/logs:/logs:rw"
        - "./redis/conf/redis.conf:/usr/local/etc/redis/redis.conf:rw"
      networks:
        - net-app
networks:
    net-app:
